import { ref, computed } from 'vue'
import { defineStore } from 'pinia'

export const useCharacterStore = defineStore('characters', () => {
  const characters = ref([
    { 
      name: "Zeus", 
      id: "zeus", 
      image: "/zeus.png", 
      symbols: ["Blesk", "Orel"], 
      father: ["kronos"], 
      mother: ["rhea"], 
      children: ["afrodita", "appolon", "artemis"], 
      home: ["Hora Olymp"], partners: ["hera"], 
      siblings: ["hestia", "hades", "hera", "poseidon", "demeter"],
      info: [
        "Zeus je olympský bůh oblohy a hromu, král všech ostatních bohů a lidí, a je tak vnímán jako hlavní postava řecké mytologie.", 
        "Většinou bývá zobrazen s žezlem v jedné ruce a s bleskem v druhé, obě symbolizují jeho autoritu. Homérem byl často popisován jako \"nositel egidy\", což je obrovský štít, který s sebou občas nosil.", 
        "Často byl spojován s moudrostí, vědomím, autoritou, osudem, bitvami a mocí."
      ],
      bio: [
        "Je paradoxně nejstarším i nejmladším synem titánů Krona a Rhei. Kronos, který svrhnul svého otce Urana, se dozvěděl, že jeden z jeho potomků ho také svrhne a tak je začal hned po narození polykat. Takto bylo spolknuto jeho pět sourozenců. Zeus by byl také spolykán, ale Rhea místo toho dala Kronovi zabalený kámen a Dia schovala v jeskyni na krétské hoře Ida.",
        "V této jeskyni byl vychován nymfami a poznal svou první manželku, Métis - bohyni rozumu. Díky jejím radám se přestrojil jako olympijský nosič pohárů a přiměl Krona, aby vypil otrávené víno. Z tohoto vína zvracel natolik, že vyzvracel Diovy sourozence, kteří byli připraveni na pomstu.",
        "Tímto začala válka mezi Titány a Olympskými bohy, která skončila nevyhnutelným svržením Krona.", 
        "Po svržení svého otce byl čas rozdělit svět mezi jeho tři syny. Udělali to formou losování, Poseidón dostal moře, Hádés podsvětí a Zeus nebe. Poté byl korunován jako vládce všech bohů."
      ],
      facts: [
        "Měl dohromady 26 dětí.", 
        "Svou první manželku spolykal, když se dozvěděl, že jeho dítě by pro něj mohlo být hrozbou. Tímto dítětem byla bohyně moudrosti Athéna, která se nakonec narodila z Diova čela.", 
        "Je jednou z nejvíce nevěrných postav z celé řecké mytologie."
      ]
    },
    {
      name: "Poseidón",
      id: "poseidon",
      image: "/poseidon.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Héra",
      id: "hera",
      image: "/hera.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Árés",
      id: "ares",
      image: "/ares.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Athéna",
      id: "athena",
      image: "/athena.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Appolón",
      id: "appolon",
      image: "/apollon.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Afrodita",
      id: "afrodita",
      image: "/afrodita.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Hermés",
      id: "hermes",
      image: "/hermes.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Artemis",
      id: "artemis",
      image: "/artemis.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Hefaistós",
      id: "hefaistos",
      image: "/hefaistos.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Démétér",
      id: "demeter",
      image: "/demeter.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Hádés",
      id: "hades",
      image: "/hades.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Hestia",
      id: "hestia",
      image: "/hestia.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Dionýsos",
      id: "dionysos",
      image: "/dionysos.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Chaos",
      id: "chaos",
      image: "/chaos.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Erebos",
      id: "erebos",
      image: "/erebos.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Gaia",
      id: "gaia",
      image: "/gaia.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Uranos",
      id: "uranos",
      image: "/uranos.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Nyx",
      id: "nyx",
      image: "/nyx.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Pontos",
      id: "pontos",
      image: "/pontos.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Tartarus",
      id: "tartarus",
      image: "/tartarus.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Múzy",
      id: "muzy",
      image: "/muzy.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Pan",
      id: "pan",
      image: "/pan.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Grácie",
      id: "gracie",
      image: "/gracie.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Sudičky",
      id: "sudicky",
      image: "/sudicky.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Adónis",
      id: "adonis",
      image: "/adonis.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Charón",
      id: "charon",
      image: "/charon.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Seléné",
      id: "selene",
      image: "/selene.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Thanatos",
      id: "thanatos",
      image: "/thanatos.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Kronos",
      id: "kronos",
      image: "/kronos.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Okeanos",
      id: "okeanos",
      image: "/okeanos.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Atlas",
      id: "atlas",
      image: "/atlas.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Prometheus",
      id: "prometheus",
      image: "/prometheus.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Hyperión",
      id: "hyperion",
      image: "/hyperion.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Rhea",
      id: "rhea",
      image: "/rhea.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Styx",
      id: "styx",
      image: "/styx.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Létó",
      id: "leto",
      image: "/leto.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Iapetos",
      id: "iapetos",
      image: "/iapetos.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Koios",
      id: "koios",
      image: "/koios.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Krios",
      id: "krios",
      image: "/krios.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Mnémosyné",
      id: "mnemosyne",
      image: "/mnemosyne.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Foibé",
      id: "foibe",
      image: "/foibe.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Téthys",
      id: "tethys",
      image: "/tethys.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Theia",
      id: "theia",
      image: "/theia.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Themis",
      id: "themis",
      image: "/themis.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Perseus",
      id: "perseus",
      image: "/perseus.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Odysseus",
      id: "odysseus",
      image: "/odysseus.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Achilles",
      id: "achilles",
      image: "/achilles.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Orfeus",
      id: "orfeus",
      image: "/orfeus.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Héraklés",
      id: "herakles",
      image: "/herakles.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Théseus",
      id: "theseus",
      image: "/theseus.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Kentauři",
      id: "kentauri",
      image: "/kentauri.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Dryády",
      id: "dryady",
      image: "/dryady.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Najády",
      id: "najady",
      image: "/najady.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Nymfy",
      id: "nymfy",
      image: "/muzy.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Satyrové",
      id: "satyrove",
      image: "/satyrove.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Sirény",
      id: "sireny",
      image: "/sireny.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Sfinx",
      id: "sfinx",
      image: "/sfinx.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Obři",
      id: "obri",
      image: "/obri.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Gorgony",
      id: "gorgony",
      image: "/gorgony.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
    {
      name: "Harpyje",
      id: "harpyje",
      image: "/harpyje.jpg",
      symbols: [],
      father: [],
      mother: [],
      children: [],
      home: [],
      partners: [],
      siblings: [],
      info: [],
      bio: [],
      facts: []
    },
  ]);

  return { characters };
})